### PR TITLE
Update from GCM to FCM

### PR DESCRIPTION
**Pull request by CVeniamin**
Since Twilio has updated their docs and android quickstart. Also, the current TwilioSDK version is at `2.0.0-beta4` which will be soon deprecated. 
Following changes have been made :
- Update from GCM to FCM
- Removed `GCMRegistrationService` that extends `IntentService` because Android O doesn't allow `IntentService` anymore as per [twilio android quickstart](https://github.com/twilio/voice-quickstart-android/) and [android docs](https://developer.android.com/about/versions/oreo/background)
- Changed name from `com.phonegap.plugins.twiliovoice` to more conventional cordova naming `cordova-plugin-twiliovoice` 
- Fixed the version on `plugin.xml` to match `package.json`
- Removed `disconnect` sound since wasn't used at all on android

### CODE REVIEW

**Comment by lyngbach** [comment]
Nice work! Hopefully this will get merged soon :)


..My OCD thank you for the naming change!

**Comment by jefflinwood** [comment]
Wow, great work!

**Comment by CVeniamin** [comment]
@jefflinwood, Thanks for merging this PR! 
I installed the plugin locally to make sure it's working, however after a quick look at `plugin.xml` I noticed that [plugin.xml L88]( https://github.com/jefflinwood/twilio-voice-phonegap-plugin/blob/master/plugin.xml#L88) should also be removed since it can produce errors when cordova cli doesn't find that resource on `sounds` folder. 
I can't explain why cordova didn't complain for this resource...

**Comment by jefflinwood** [comment]
Strange! Ok, if you push a new commit, and make a new PR, I can merge it pretty quick.

**Comment by CVeniamin** [comment]
@jefflinwood, done, look at #43

**Pull request merged**
